config/routes.rb
Rails.application.routes.draw do
  default_url_options host: '123leadmagnets.com'

  root 'static_pages#home'
  get '/about', to: 'sales_pages#about'

  # Payments
  resources :payments
  get '/thank-you', to: 'payments#thank_you'
  get '/sign-up-offer', to: 'sales_pages#sign_up_offer'

  # Content
  resources :podcasts
  resources :articles
  resources :contents
  resources :courses do
    resources :course_modules, path: :modules
  end
  resources :course_modules

  # REFERRAL PROGRAM
  # resources :referred_users
  get 'unlock' => 'referred_users#new'
  resources :referred_users, only: [:create]
  # post 'referred_users/create' => 'referred_users#create'
  get 'refer-a-friend' => 'referred_users#refer'
  get '/referrer/:id' => 'referred_users#confirm_and_set_referrer_cookie'

  # Legal
  get '/terms', to: 'static_pages#terms'
  get '/privacy', to: 'static_pages#privacy'
  get '/content-licensing', to: 'static_pages#content_licensing'

  # Error Pages
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unacceptable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Patterns
  get '/patterns' => 'static_pages#patterns'

  resources :cart_items, only: %i[create destroy]

  # SITE MAP
  get '/sitemap.xml' => 'sitemaps#index', defaults: { format: 'xml' }
  # ROBOTS
  get '/robots.:format', to: 'robots#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations' }
  ActiveAdmin.routes(self)

  # Home
  get '/dashboard', to: 'home#index'
end

app/models/content.rb
class Content < ApplicationRecord
  has_rich_text :body
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @contents = Content.all
  end

  def new
    @needs_trix = true
    @content = Content.new
  end

  def create
    @content = Content.new(content_params)
    if @content.save
      flash[:success] = 'content created successfully! :D'
      redirect_to edit_content_path(@content)
    else
      flash[:alert] = 'content failed to create :('
      render 'new'
    end
  end

  def edit
    @needs_trix = true
    @content = Content.find(params[:id])
  end

  def update
    @content = Content.find(params[:id])
    if @content.update(content_params)
      flash[:success] = 'content updated successfully! :D'
      redirect_to edit_content_path(@content)
    else
      flash[:alert] = 'content failed to update :('
      render 'edit'
    end
  end

  private

  def content_params
    params.require(:content).permit(:identifier, :body)
  end
end

app/views/contents/_form.html.haml
= semantic_form_for @content do |f|
  = f.input :identifier
  = f.label :body
  = f.rich_text_area :body
  .actions
    = f.actions do
      = f.action :submit, :as => :input, :button_html => {  class: 'btn btn-lg btn-primary' }

app/views/contents/edit.html.haml
.container.my-5
  %h1 Editing content

  = render 'form'

app/views/contents/index.html.haml
%h1 Listing contents

%table
  %thead
    %tr
      %th Identifier
      %th Body
      %th
      %th
      %th

  %tbody
    - @contents.each do |content|
      %tr
        %td= content.identifier
        %td= content.body
        %td= link_to 'Show', content
        %td= link_to 'Edit', edit_content_path(content)
        %td= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Content', new_content_path

app/views/contents/new.html.haml
.container.my-5
  %h1 New content

  = render 'form'