config/routes.rb
Rails.application.routes.draw do
  default_url_options host: '123leadmagnets.com'

  root 'static_pages#home'
  get '/about', to: 'sales_pages#about'

  # Payments
  resources :payments
  get '/thank-you', to: 'payments#thank_you'
  get '/sign-up-offer', to: 'sales_pages#sign_up_offer'

  # Content
  resources :podcasts
  resources :articles
  resources :contents
  resources :courses do
    resources :course_modules, path: :modules
  end
  resources :course_modules

  # REFERRAL PROGRAM
  # resources :referred_users
  get 'unlock' => 'referred_users#new'
  resources :referred_users, only: [:create]
  # post 'referred_users/create' => 'referred_users#create'
  get 'refer-a-friend' => 'referred_users#refer'
  get '/referrer/:id' => 'referred_users#confirm_and_set_referrer_cookie'

  # Legal
  get '/terms', to: 'static_pages#terms'
  get '/privacy', to: 'static_pages#privacy'
  get '/content-licensing', to: 'static_pages#content_licensing'

  # Error Pages
  match '/404', to: 'errors#not_found', via: :all
  match '/422', to: 'errors#unacceptable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  # Patterns
  get '/patterns' => 'static_pages#patterns'

  resources :cart_items, only: %i[create destroy]

  # SITE MAP
  get '/sitemap.xml' => 'sitemaps#index', defaults: { format: 'xml' }
  # ROBOTS
  get '/robots.:format', to: 'robots#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations' }
  ActiveAdmin.routes(self)

  # Home
  get '/dashboard', to: 'home#index'
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  before_save { email.downcase! }

  after_create :register_with_active_campaign

  def register_with_active_campaign
    ActiveCampaignEventHandler::InternalEventAPI.bought_library_pass(email) if products.include? 'Lead Magnets'
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!, only: [:apply_share_discount]

  def new
    @payment = Payment.new
  end

  def create
    # process/determine "offer" (based on params):
    # - price
    # - products
    offer = OfferDeterminer.determine_based_on(payment_params)

    begin
      # stripe customer should be on User.
      customer = Stripe::Customer.create({
                                           source: stripe_token,
                                           email: payment_params[:email]
                                         })

      charge = Stripe::Charge.create({
                                       amount: offer.price,
                                       currency: 'usd',
                                       description: 'Mark Sing Coaching',
                                       customer: customer.id
                                     })

      payment = Payment.new(
        amount: offer.price,
        email: payment_params[:email],
        paid: true,
        products: offer.products,
        stripe_charge_id: charge.id,
        stripe_customer_id: customer.id
      )

      if payment.save
        flash[:success] = 'Success! Your purchase was successful! Go conquer the world!'
      else
        flash[:notice] = 'There was an error with your payment.'
      end
    rescue StandardError => e
      flash[:notice] = e.message
    end

    redirect_to payment
  end

  def show
    @payment = Payment.find(params[:id])
    @resource = User.new(email: @payment.email) unless current_user
  end

  def apply_share_discount
    current_user.apply_discount = true
    if current_user.save
      flash[:success] = 'Thank you for your support! You now have 50% OFF 😁'
    else
      flash[:notice] = 'Something went wrong... contact us to get it resolved.'
    end
    redirect_to '/dashboard'
  end

  private

  def payment_params
    params.require(:payment).permit(:email, :opted_into_offer, :sign_up_offer, :content_generator, :lead_magnet_id, :cart_id, :stripeToken)
  end

  def stripe_token
    payment_params[:stripeToken]
  end
end

app/views/payments/_form.html.haml
= semantic_form_for Payment.new, html: { id: 'payment-form' } do |f|

  = f.inputs do
    - if current_user
      .text-center
        %small= "Signed in as #{current_user.email}."
      = f.hidden_field :user_id, value: current_user.id
      = f.hidden_field :email, value: current_user.email
    - else 
      = f.label :email
      = f.email_field :email, class: "form-control mb-3"
    = f.label 'Credit or Debit Card'

    #card-element
    #card-errors{ role: 'alert' }

    - if @lead_magnet
      = f.hidden_field :lead_magnet_id, value: @lead_magnet.id

    - if @cart
      = f.hidden_field :cart_id, value: @cart.id

    - if sign_up_offer
      = f.hidden_field :sign_up_offer, value: true

    - if content_generator
      = f.hidden_field :content_generator, value: true

    - if social_media_oto
      %label#exclusive-offer.w-100.m-0.mt-3
        .jumbotron.m-0.p-3
          .text-center.mb-3
            %input{"aria-label" => "Checkbox for following text input", :type => "checkbox", name: 'payment[opted_into_offer]'}
              %span.font-weight-bold Yes! Give Me the Social Media Marketing Courses too!
          %p.mb-1
            %span.font-weight-bold ONE TIME OFFER:
            Want 30+ videos that help you start with Facebook, Instagram, and TikTok Ads? Add to your order now for
            %span.font-weight-bold ONLY $29! 
          .text-center
            %small
              This offer is not available at ANY other time or place

    .text-center.mt-3
      = f.submit 'COMPLETE ORDER NOW', class: 'btn btn-lg px-5 py-3  btn-primary m-auto', data: { disable_with: false }

:javascript
  $(document).on('DOMContentLoaded', function() {
    // Create a Stripe client.
    var stripe = Stripe("#{ENV['STRIPE_PUBLIC']}");

    // Create an instance of Elements.
    var elements = stripe.elements();

    // Custom styling can be passed to options when creating an Element.
    // (Note that this demo uses a wider set of styles than the guide below.)
    var style = {
      base: {
        color: '#32325d',
        fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
        fontSmoothing: 'antialiased',
        fontSize: '16px',
        '::placeholder': {
          color: '#aab7c4'
        }
      },
      invalid: {
        color: '#fa755a',
        iconColor: '#fa755a'
      }
    };

    // Create an instance of the card Element.
    var card = elements.create('card', {style: style});

    // Add an instance of the card Element into the `card-element` <div>.
    card.mount('#card-element');

    // Handle real-time validation errors from the card Element.
    card.addEventListener('change', function(event) {
      var displayError = document.getElementById('card-errors');
      if (event.error) {
        displayError.textContent = event.error.message;
      } else {
        displayError.textContent = '';
      }
    });

    // Handle form submission.
    var form = document.getElementById('payment-form');
    form.addEventListener('submit', function(event) {
      event.preventDefault();
      event.target.querySelector('*[type=submit]').disabled = true

      stripe.createToken(card).then(function(result) {
        if (result.error) {
          // Inform the user if there was an error.
          var errorElement = document.getElementById('card-errors');
          errorElement.textContent = result.error.message;
          event.target.querySelector('*[type=submit]').disabled = false
        } else {
          if (#{Rails.env.production?}) {
            fbq('track', 'Purchase', {currency: "USD", value: #{cost}});
            gtag('event', 'conversion', {
              'send_to': 'AW-630308685/VTc3CP284OwBEM3-xqwC',
              'value': #{cost},
              'currency': 'USD',
              'transaction_id': ''
            });
          }
          // Send the token to your server.
          stripeTokenHandler(result.token);
        }
      });
    });

    // Submit the form with the token ID.
    function stripeTokenHandler(token) {
      // Insert the token ID into the form so it gets submitted to the server
      var form = document.getElementById('payment-form');
      var hiddenInput = document.createElement('input');
      hiddenInput.setAttribute('type', 'hidden');
      hiddenInput.setAttribute('name', 'payment[stripeToken]');
      hiddenInput.setAttribute('value', token.id);
      form.appendChild(hiddenInput);

      // Submit the form
      form.submit();
    }
  })

app/views/payments/edit.html.haml
%h1 Editing Course Payment
= render 'form', payment: @payment
= link_to 'Show', @payment
|
= link_to 'Back', payments_path

app/views/payments/index.html.haml
%p#notice= notice
%h1 Course Payments
%table
  %thead
    %tr
      %th Course
      %th User
      %th Amount
      %th Stripe charge
      %th{:colspan => "3"}
  %tbody
    - @payments.each do |payment|
      %tr
        %td= payment.course_id
        %td= payment.user_id
        %td= payment.amount
        %td= payment.stripe_charge_id
        %td= link_to 'Show', payment
        %td= link_to 'Edit', edit_payment_path(payment)
        %td= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Course Payment', new_payment_path

app/views/payments/new.html.haml
%h1 New Course Payment
= render 'form', payment: @payment
= link_to 'Back', payments_path

app/views/payments/show.html.haml
.container
  .row.py-3.py-md-5.align-content-center.text-center
    .col-12
      %h1.super-bold
        Thank you!
      %h5 Your business is highly valued and we strive to serve.
  .row
    .col-12.col-md-8.offset-md-2
      %p Here is your receipt and payment details:
      %table.table.table-bordered
        %tbody
          %tr
            %td.font-weight-bold Purchase ID
            %td= @payment.id
          %tr
            %td.font-weight-bold Cost
            %td= "$#{@payment.amount / 100}"

.container.py-5
  .row
    - if current_user
      .col-12.text-center
        %a.btn.btn-primary.py-3.px-5{ href: library_path }
          Go to Your Library
        %br
        %a.mt-3{ href: dashboard_path }
          Or go to Dashboard >
    - else 
      .col-12.col-sm-8.offset-sm-2.col-md-6.offset-md-3
        %h2 Set a password to access your new account
        = render 'devise/registrations/new'
        %a{ href: new_user_session_path }